### ISSUE TITLE
cacsca

### ISSUE THREAD

**Issue by JuneLin2001** [JuneLin2001/91APP_front-end-class#31]
cacsca

**Comment by rebeccaS47** [comment]
ccccc

**Comment by rebeccaS47** [comment]
dssssssss

**Comment by rebeccaS47** [comment]
ssss

**Comment by rebeccaS47** [comment]
ssssaaaaaaaa

**Comment by rebeccaS47** [comment]
~~~~~~

**Comment by rebeccaS47** [comment]
aaaaaaaa

**Comment by hsin-2333** [comment]
# A demo of `react-markdown`

`react-markdown` is a markdown component for React.

👉 Changes are re-rendered as you type.

👈 Try writing some markdown on the left.

## Overview


* Follows [CommonMark](https://commonmark.org)
* Optionally follows [GitHub Flavored Markdown](https://github.github.com/gfm/)
* Renders actual React elements instead of using `dangerouslySetInnerHTML`
* Lets you define your own components (to render `MyHeading` instead of `'h1'`)
* Has a lot of plugins

## Contents
